version: '3.4'

services:
  readingisgood70.api:
    image: readingisgood70:dev
    container_name: ReadingIsGood70.Api
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "ReadingIsGood70.Api"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - /Users/cihadturan/ReadingIsGood70/ReadingIsGood70/ReadingIsGood70.Api:/app
      - /Users/cihadturan/ReadingIsGood70/ReadingIsGood70:/src
      - /Users/cihadturan/vsdbg/vs2017u5:/remote_debugger:rw
      - /Users/cihadturan/.nuget/packages/:/root/.nuget/packages:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/net7.0/ReadingIsGood70.Api.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true